 // Generated by https://quicktype.io

class User {
  UserClass user;
  String token;

  User({
    this.user,
    this.token,
  });

  factory User.fromJson(Map<String, dynamic> json) => User(
    token : json['token'],
    user  : UserClass.fromJson(json['user'])
  );
  

  
}

class UserClass {
  bool status;
  bool google;
  String name;
  String email;
  String rol;
  String uid;

  UserClass({
    this.status,
    this.google,
    this.name,
    this.email,
    this.rol,
    this.uid,
  });
  factory UserClass.fromJson(Map<String, dynamic> json) => UserClass(
    status : json['status'],
    google : json['google'],
    name : json['name'],
    email : json['email'],
    rol : json['rol'],
    uid : json['uid']

  );

  Map<String, dynamic> toJson() => {
    "status": status,
    "google": google,
    "name": name,
    "email": email,
    "rol": rol,
    "uid": uid
  };
}
